### ISSUE TITLE
ReferenceError: dartColor is not defined

### ISSUE THREAD

**Issue by woaiios** [thize/xd-to-flutter#23]
https://github.com/thize/xd-to-flutter/blob/844bf98be134a5db64a0b561ed90ee32fecda535/src/export_all.js#L190

`ReferenceError: dartColor is not defined`

```
/Users/xxxxxx/Library/Application Support/Adobe/Adobe XD/develop/xd-to-flutter/src/export_all.js:190
        colors.push(dartColor(colorStop.color));
               ^
Plugin ReferenceError: dartColor is not defined
    at <settings>/develop/xd-to-flutter/src/export_all.js:190:16
    at Array.forEach (<anonymous>)
    at _gradientColorList (<settings>/develop/xd-to-flutter/src/export_all.js:189:25)
    at <settings>/develop/xd-to-flutter/src/export_all.js:68:59
    at Array.forEach (<anonymous>)
    at exportAllColors (<settings>/develop/xd-to-flutter/src/export_all.js:66:18)
    at exportAll (<settings>/develop/xd-to-flutter/src/export_all.js:22:9)
    at <settings>/develop/xd-to-flutter/src/ui/main_panel_ui.js:88:9
    at e.exports.<anonymous> (<settings>/develop/xd-to-flutter/src/ui/main_panel_ui.js:122:13)
    at e.exports.p (uxp://uxp-internal/domjs_scripts.js:2:24351)

```

**Comment by fanterxissss** [comment]
我爱ios？这是你的名字吗？
